### ISSUE TITLE
Add proper CSS id's and classes for better theme development

### ISSUE THREAD

**Issue by QazCetelic** [revoltchat/themes#25] opened 2021-12-30 15:29 UTC
Currently, the chat background is called `sc-bYEvvW` which is far from intuitive and the other classes have similar names.
My suggestion is to create human-readable CSS classes or tweak the CSS post processor.

**Comment by insertish** [comment] 2021-12-30 15:30
Duplicate of https://github.com/revoltchat/revite/issues/149

**Closed by insertish** 2021-12-30 15:30 UTC
